# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff92cca584c0d9fc8313ddadee00f22e37b2ff2f81be6b70e9fa5132efd44032e4d71bc598a0054aa610c1aae45d501052eef9aae331df9e87a2be2c292e1ea8

test:
  secret_key_base: 288b3fb71ee85a2ca2905d0907032584750f4639a7621047a0e3ec21b262e09d32b5fca949a3d91e48f0b5c00e9b15f9c29eb45d36c5e0674c1a69476425c9f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  email_provider_username: <%= ENV["USER_NAME"] %>
  email_provider_password: <%= ENV["PASSWORD"] %>
  my_password: <%= ENV["MY_PASSWORD"] %>